CREATE TABLE warehouse_schema.dim_date (
	date_key int8 NOT NULL,
	full_date date NOT NULL,
	day_of_week int8 NULL,
	day_num_in_month int8 NULL,
	day_num_overall int8 NULL,
	day_name varchar(9) NULL,
	day_abbrev bpchar(3) NULL,
	weekday_flag varchar(50) NULL,
	week_num_in_year int8 NULL,
	week_num_overall int8 NULL,
	week_begin_date date NULL,
	week_begin_date_key int8 NULL,
	"month" int8 NULL,
	month_num_overall int8 NULL,
	month_name varchar(9) NULL,
	month_abbrev bpchar(3) NULL,
	quarter int8 NULL,
	"year" int8 NULL,
	yearmo int8 NULL,
	fiscal_month int8 NULL,
	fiscal_quarter int8 NULL,
	fiscal_year int8 NULL,
	last_day_in_month_flag varchar(50) NULL,
	same_day_year_ago_date date NULL,
	CONSTRAINT dim_date_pkey PRIMARY KEY (date_key)
);